
classdef Control_Surfaces < ros.Message
    %Control_Surfaces MATLAB implementation of cosmus_messages/Control_Surfaces
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_messages/Control_Surfaces' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c0ac844265baab4b8605462ecb45014a' % The MD5 Checksum of the message definition
        PropertyList = { 'Propeller' 'RightAileron' 'RightFlap' 'Elevators' 'Rudder' } % List of non-constant message properties
        ROSPropertyList = { 'propeller' 'right_aileron' 'right_flap' 'elevators' 'rudder' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Propeller
        RightAileron
        RightFlap
        Elevators
        Rudder
    end
    methods
        function set.Propeller(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Control_Surfaces', 'Propeller');
            obj.Propeller = double(val);
        end
        function set.RightAileron(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Control_Surfaces', 'RightAileron');
            obj.RightAileron = double(val);
        end
        function set.RightFlap(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Control_Surfaces', 'RightFlap');
            obj.RightFlap = double(val);
        end
        function set.Elevators(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Control_Surfaces', 'Elevators');
            obj.Elevators = double(val);
        end
        function set.Rudder(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Control_Surfaces', 'Rudder');
            obj.Rudder = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_messages.Control_Surfaces.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_messages.Control_Surfaces(strObj);
        end
    end
end
