
classdef Datagram < ros.Message
    %Datagram MATLAB implementation of cosmus_messages/Datagram
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_messages/Datagram' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7602d23a0a18163d5a4467de20435330' % The MD5 Checksum of the message definition
        PropertyList = { 'Data' 'Ssid' } % List of non-constant message properties
        ROSPropertyList = { 'data' 'ssid' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.cosmus_messages.Vector3D' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Data
        Ssid
    end
    methods
        function set.Data(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.cosmus_messages.Vector3D'};
            validateattributes(val, validClasses, validAttributes, 'Datagram', 'Data')
            obj.Data = val;
        end
        function set.Ssid(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Datagram', 'Ssid');
            obj.Ssid = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_messages.Datagram.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_messages.Datagram(strObj);
        end
    end
end
