
classdef NetworkComm < ros.Message
    %NetworkComm MATLAB implementation of cosmus_communication/NetworkComm
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_communication/NetworkComm' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f99a2806168ccdb6dbe38563e2107558' % The MD5 Checksum of the message definition
        PropertyList = { 'Comms' } % List of non-constant message properties
        ROSPropertyList = { 'comms' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.cosmus_communication.Communication' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Comms
    end
    methods
        function set.Comms(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.cosmus_communication.Communication.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.cosmus_communication.Communication'};
            validateattributes(val, validClasses, validAttributes, 'NetworkComm', 'Comms')
            obj.Comms = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_communication.NetworkComm.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_communication.NetworkComm(strObj);
        end
    end
end
