
classdef Odom < ros.Message
    %Odom MATLAB implementation of cosmus_communication/Odom
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_communication/Odom' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd43b451da51ce77be7284875a2ca7854' % The MD5 Checksum of the message definition
        PropertyList = { 'Pitch' 'Roll' 'Yaw' 'PositionX' 'PositionY' 'PositionZ' 'Velocity' } % List of non-constant message properties
        ROSPropertyList = { 'pitch' 'roll' 'yaw' 'position_x' 'position_y' 'position_z' 'velocity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pitch
        Roll
        Yaw
        PositionX
        PositionY
        PositionZ
        Velocity
    end
    methods
        function set.Pitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Pitch');
            obj.Pitch = double(val);
        end
        function set.Roll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Roll');
            obj.Roll = double(val);
        end
        function set.Yaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Yaw');
            obj.Yaw = double(val);
        end
        function set.PositionX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'PositionX');
            obj.PositionX = double(val);
        end
        function set.PositionY(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'PositionY');
            obj.PositionY = double(val);
        end
        function set.PositionZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'PositionZ');
            obj.PositionZ = double(val);
        end
        function set.Velocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Velocity');
            obj.Velocity = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_communication.Odom.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_communication.Odom(strObj);
        end
    end
end
