// Generated by gencpp from file cosmus_messages/Airspeed.msg
// DO NOT EDIT!


#ifndef COSMUS_MESSAGES_MESSAGE_AIRSPEED_H
#define COSMUS_MESSAGES_MESSAGE_AIRSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cosmus_messages/Vector3D.h>

namespace cosmus_messages
{
template <class ContainerAllocator>
struct Airspeed_
{
  typedef Airspeed_<ContainerAllocator> Type;

  Airspeed_()
    : header()
    , differential_pressure(0.0)
    , intensity(0.0)
    , velocity()  {
    }
  Airspeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , differential_pressure(0.0)
    , intensity(0.0)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _differential_pressure_type;
  _differential_pressure_type differential_pressure;

   typedef float _intensity_type;
  _intensity_type intensity;

   typedef  ::cosmus_messages::Vector3D_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::cosmus_messages::Airspeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cosmus_messages::Airspeed_<ContainerAllocator> const> ConstPtr;

}; // struct Airspeed_

typedef ::cosmus_messages::Airspeed_<std::allocator<void> > Airspeed;

typedef boost::shared_ptr< ::cosmus_messages::Airspeed > AirspeedPtr;
typedef boost::shared_ptr< ::cosmus_messages::Airspeed const> AirspeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cosmus_messages::Airspeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cosmus_messages::Airspeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cosmus_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cosmus_messages': ['/home/fabricio/catkin_ws/src/COSMUS_gnc/gnc_messages/matlab_msg_gen_ros1/glnxa64/src/cosmus_messages/msg'], 'std_msgs': ['/home/fabricio/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/fabricio/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_messages::Airspeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_messages::Airspeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_messages::Airspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_messages::Airspeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_messages::Airspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_messages::Airspeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cosmus_messages::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b503fe4a6b8d1e7d3f42ab23d304a71b";
  }

  static const char* value(const ::cosmus_messages::Airspeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb503fe4a6b8d1e7dULL;
  static const uint64_t static_value2 = 0x3f42ab23d304a71bULL;
};

template<class ContainerAllocator>
struct DataType< ::cosmus_messages::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cosmus_messages/Airspeed";
  }

  static const char* value(const ::cosmus_messages::Airspeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cosmus_messages::Airspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header # header\n"
"float32 differential_pressure\n"
"# float32 temperature\n"
"float32 intensity\n"
"cosmus_messages/Vector3D velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cosmus_messages/Vector3D\n"
"# ingroup subt_msgs\n"
"# interface Datagram\n"
"# A message containing some payload to communicate among one or\n"
"# multiple teammates.\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::cosmus_messages::Airspeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cosmus_messages::Airspeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.differential_pressure);
      stream.next(m.intensity);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Airspeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cosmus_messages::Airspeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cosmus_messages::Airspeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "differential_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.differential_pressure);
    s << indent << "intensity: ";
    Printer<float>::stream(s, indent + "  ", v.intensity);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::cosmus_messages::Vector3D_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSMUS_MESSAGES_MESSAGE_AIRSPEED_H
