// Generated by gencpp from file cosmus_messages/WifiSignals.msg
// DO NOT EDIT!


#ifndef COSMUS_MESSAGES_MESSAGE_WIFISIGNALS_H
#define COSMUS_MESSAGES_MESSAGE_WIFISIGNALS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cosmus_messages/WifiSignal.h>

namespace cosmus_messages
{
template <class ContainerAllocator>
struct WifiSignals_
{
  typedef WifiSignals_<ContainerAllocator> Type;

  WifiSignals_()
    : signals()  {
    }
  WifiSignals_(const ContainerAllocator& _alloc)
    : signals(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cosmus_messages::WifiSignal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cosmus_messages::WifiSignal_<ContainerAllocator> >::other >  _signals_type;
  _signals_type signals;





  typedef boost::shared_ptr< ::cosmus_messages::WifiSignals_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cosmus_messages::WifiSignals_<ContainerAllocator> const> ConstPtr;

}; // struct WifiSignals_

typedef ::cosmus_messages::WifiSignals_<std::allocator<void> > WifiSignals;

typedef boost::shared_ptr< ::cosmus_messages::WifiSignals > WifiSignalsPtr;
typedef boost::shared_ptr< ::cosmus_messages::WifiSignals const> WifiSignalsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cosmus_messages::WifiSignals_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cosmus_messages::WifiSignals_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cosmus_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'cosmus_messages': ['/home/fabricio/catkin_ws/src/COSMUS_gnc/gnc_messages/matlab_msg_gen_ros1/glnxa64/src/cosmus_messages/msg'], 'std_msgs': ['/home/fabricio/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/fabricio/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_messages::WifiSignals_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_messages::WifiSignals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_messages::WifiSignals_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb437e1a1feb5032f44a292619f5c288";
  }

  static const char* value(const ::cosmus_messages::WifiSignals_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb437e1a1feb5032ULL;
  static const uint64_t static_value2 = 0xf44a292619f5c288ULL;
};

template<class ContainerAllocator>
struct DataType< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cosmus_messages/WifiSignals";
  }

  static const char* value(const ::cosmus_messages::WifiSignals_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n"
"# Administrator of the National Aeronautics and Space Administration.\n"
"#\n"
"# All rights reserved.\n"
"#\n"
"# The Astrobee platform is licensed under the Apache License, Version 2.0\n"
"# (the \"License\"); you may not use this file except in compliance with the\n"
"# License. You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n"
"# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n"
"# License for the specific language governing permissions and limitations\n"
"# under the License.\n"
"#\n"
"# A Wifi signal characteristics\n"
"\n"
"cosmus_messages/WifiSignal[] signals        # signals\n"
"\n"
"================================================================================\n"
"MSG: cosmus_messages/WifiSignal\n"
"# Copyright (c) 2017, United States Government, as represented by the\n"
"# Administrator of the National Aeronautics and Space Administration.\n"
"#\n"
"# All rights reserved.\n"
"#\n"
"# The Astrobee platform is licensed under the Apache License, Version 2.0\n"
"# (the \"License\"); you may not use this file except in compliance with the\n"
"# License. You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n"
"# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n"
"# License for the specific language governing permissions and limitations\n"
"# under the License.\n"
"#\n"
"# A Wifi signal characteristics\n"
"\n"
"string ssid            # name of AP\n"
"float32   signal_dbm      # dBm\n"
"float32  frequency        # Hz\n"
;
  }

  static const char* value(const ::cosmus_messages::WifiSignals_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WifiSignals_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cosmus_messages::WifiSignals_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cosmus_messages::WifiSignals_<ContainerAllocator>& v)
  {
    s << indent << "signals[]" << std::endl;
    for (size_t i = 0; i < v.signals.size(); ++i)
    {
      s << indent << "  signals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cosmus_messages::WifiSignal_<ContainerAllocator> >::stream(s, indent + "    ", v.signals[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSMUS_MESSAGES_MESSAGE_WIFISIGNALS_H
