// Generated by gencpp from file cosmus_communication/Communication.msg
// DO NOT EDIT!


#ifndef COSMUS_COMMUNICATION_MESSAGE_COMMUNICATION_H
#define COSMUS_COMMUNICATION_MESSAGE_COMMUNICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cosmus_communication
{
template <class ContainerAllocator>
struct Communication_
{
  typedef Communication_<ContainerAllocator> Type;

  Communication_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Communication_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::cosmus_communication::Communication_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cosmus_communication::Communication_<ContainerAllocator> const> ConstPtr;

}; // struct Communication_

typedef ::cosmus_communication::Communication_<std::allocator<void> > Communication;

typedef boost::shared_ptr< ::cosmus_communication::Communication > CommunicationPtr;
typedef boost::shared_ptr< ::cosmus_communication::Communication const> CommunicationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cosmus_communication::Communication_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cosmus_communication::Communication_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cosmus_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/fabricio/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'cosmus_communication': ['/home/fabricio/catkin_ws/src/COSMUS_gnc/gnc_messages/matlab_msg_gen_ros1/glnxa64/src/cosmus_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_communication::Communication_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cosmus_communication::Communication_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_communication::Communication_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cosmus_communication::Communication_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_communication::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cosmus_communication::Communication_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cosmus_communication::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44258f22707aa08ca1ea7bce44760002";
  }

  static const char* value(const ::cosmus_communication::Communication_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44258f22707aa08cULL;
  static const uint64_t static_value2 = 0xa1ea7bce44760002ULL;
};

template<class ContainerAllocator>
struct DataType< ::cosmus_communication::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cosmus_communication/Communication";
  }

  static const char* value(const ::cosmus_communication::Communication_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cosmus_communication::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cosmus_communication::Communication_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cosmus_communication::Communication_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Communication_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cosmus_communication::Communication_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cosmus_communication::Communication_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSMUS_COMMUNICATION_MESSAGE_COMMUNICATION_H
