
classdef Odom < ros.Message
    %Odom MATLAB implementation of cosmus_messages/Odom
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_messages/Odom' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '72f22abb232776c0662f9d27ecf4bef9' % The MD5 Checksum of the message definition
        PropertyList = { 'Pitch' 'Roll' 'Yaw' 'AccelX' 'AccelY' 'AccelZ' } % List of non-constant message properties
        ROSPropertyList = { 'pitch' 'roll' 'yaw' 'accel_x' 'accel_y' 'accel_z' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pitch
        Roll
        Yaw
        AccelX
        AccelY
        AccelZ
    end
    methods
        function set.Pitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Pitch');
            obj.Pitch = double(val);
        end
        function set.Roll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Roll');
            obj.Roll = double(val);
        end
        function set.Yaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'Yaw');
            obj.Yaw = double(val);
        end
        function set.AccelX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'AccelX');
            obj.AccelX = double(val);
        end
        function set.AccelY(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'AccelY');
            obj.AccelY = double(val);
        end
        function set.AccelZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odom', 'AccelZ');
            obj.AccelZ = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_messages.Odom.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_messages.Odom(strObj);
        end
    end
end
