
classdef WifiSignals < ros.Message
    %WifiSignals MATLAB implementation of cosmus_messages/WifiSignals
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_messages/WifiSignals' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'fb437e1a1feb5032f44a292619f5c288' % The MD5 Checksum of the message definition
        PropertyList = { 'Signals' } % List of non-constant message properties
        ROSPropertyList = { 'signals' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.cosmus_messages.WifiSignal' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Signals
    end
    methods
        function set.Signals(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.cosmus_messages.WifiSignal.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.cosmus_messages.WifiSignal'};
            validateattributes(val, validClasses, validAttributes, 'WifiSignals', 'Signals')
            obj.Signals = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_messages.WifiSignals.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_messages.WifiSignals(strObj);
        end
    end
end
