
classdef WifiSignal < ros.Message
    %WifiSignal MATLAB implementation of cosmus_messages/WifiSignal
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cosmus_messages/WifiSignal' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '78a42198664f79cded956369f4e3d801' % The MD5 Checksum of the message definition
        PropertyList = { 'Ssid' 'SignalDbm' 'Frequency' } % List of non-constant message properties
        ROSPropertyList = { 'ssid' 'signal_dbm' 'frequency' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Ssid
        SignalDbm
        Frequency
    end
    methods
        function set.Ssid(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'WifiSignal', 'Ssid');
            obj.Ssid = char(val);
        end
        function set.SignalDbm(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'WifiSignal', 'SignalDbm');
            obj.SignalDbm = single(val);
        end
        function set.Frequency(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'WifiSignal', 'Frequency');
            obj.Frequency = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cosmus_messages.WifiSignal.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cosmus_messages.WifiSignal(strObj);
        end
    end
end
