# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cosmus_messages/Control_Surfaces.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Control_Surfaces(genpy.Message):
  _md5sum = "c0ac844265baab4b8605462ecb45014a"
  _type = "cosmus_messages/Control_Surfaces"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 propeller
float64 right_aileron
float64 right_flap
float64 elevators
float64 rudder
"""
  __slots__ = ['propeller','right_aileron','right_flap','elevators','rudder']
  _slot_types = ['float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       propeller,right_aileron,right_flap,elevators,rudder

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Control_Surfaces, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.propeller is None:
        self.propeller = 0.
      if self.right_aileron is None:
        self.right_aileron = 0.
      if self.right_flap is None:
        self.right_flap = 0.
      if self.elevators is None:
        self.elevators = 0.
      if self.rudder is None:
        self.rudder = 0.
    else:
      self.propeller = 0.
      self.right_aileron = 0.
      self.right_flap = 0.
      self.elevators = 0.
      self.rudder = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.propeller, _x.right_aileron, _x.right_flap, _x.elevators, _x.rudder))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.propeller, _x.right_aileron, _x.right_flap, _x.elevators, _x.rudder,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.propeller, _x.right_aileron, _x.right_flap, _x.elevators, _x.rudder))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.propeller, _x.right_aileron, _x.right_flap, _x.elevators, _x.rudder,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
